### ISSUE TITLE
Suggested fixes for the website

### ISSUE THREAD

**Issue by melibleq** [common-workflow-language/cwl-website#89]
Hi everyone. These are some things that I can't suggest directly as code changes.

- Should all links open in a new tab?
- On https://github.com/common-workflow-language/cwl-website/edit/new-site/content/_data/home.yml, the image in `- icon: noun_ecosystem_cycle_3389565.png` is going a bit over the word "reproducibility". That happened in Brave browser (Chromium-based) and Firefox on my Linux laptop.
- Should https://deploy-preview-75--cwl-website.netlify.app/assets/img/cwlportable.png say "FOSS" instead of "F/OSS"?
- Will https://deploy-preview-75--cwl-website.netlify.app/user_guide/ be a new page? It's linked in the Getting Started page but it still doesn't exist.
- Should the "Users Gallery" section be called "User Gallery" instead?

Also, some standards are needed:
- Decide whether to use the Oxford/Serial Comma or not
- What to do with the word "analys/ze"?
- In tables (ecosystem, projects) maybe always start paragraphs with a capital letter?

Please also see a compilation of my suggestions in this review: https://github.com/common-workflow-language/cwl-website/pull/75#pullrequestreview-865249262

**Comment by swzCuroverse** [comment]
On https://github.com/common-workflow-language/cwl-website/edit/new-site/content/_data/home.yml, the image in - icon: noun_ecosystem_cycle_3389565.png is going a bit over the word "reproducibility". That happened in Brave browser (Chromium-based) and Firefox on my Linux laptop. --- this doesn't happen in my Firefox could you give the resolution so we can debug it?

**Comment by swzCuroverse** [comment]
Whenever there were lists (of contributors, participants, advisors), I removed commas and semicolons after their names in my commits ---> can you give me a link to this, I don't see in PR

**Comment by mr-c** [comment]
> * Should all links open in a new tab?

No

> * Should https://deploy-preview-75--cwl-website.netlify.app/assets/img/cwlportable.png say "FOSS" instead of "F/OSS"?

Not really, no



> * Will https://deploy-preview-75--cwl-website.netlify.app/user_guide/ be a new page? It's linked in the Getting Started page but it still doesn't exist.

The website will be published to https://www.commonwl.org ; https://www.commonwl.org/user_guide is already published

**Comment by swzCuroverse** [comment]
Should https://deploy-preview-75--cwl-website.netlify.app/assets/img/cwlportable.png say "FOSS" instead of "F/OSS"? --> I tool that directly from the paper.  So Michael would have to determine.

**Comment by melibleq** [comment]
> On https://github.com/common-workflow-language/cwl-website/edit/new-site/content/_data/home.yml, the image in - icon: noun_ecosystem_cycle_3389565.png is going a bit over the word "reproducibility". That happened in Brave browser (Chromium-based) and Firefox on my Linux laptop. --- this doesn't happen in my Firefox could you give the resolution so we can debug it?

My laptop screen is 1366 x 768 px, the browser screen is 1366 x 673 px

**Comment by melibleq** [comment]
> Whenever there were lists (of contributors, participants, advisors), I removed commas and semicolons after their names in my commits ---> can you give me a link to this, I don't see in PR

It was on community.md and governance.md

**Comment by melibleq** [comment]
My review is now at https://github.com/common-workflow-language/cwl-website/pull/75#pullrequestreview-865249262

**Comment by melibleq** [comment]
> > On https://github.com/common-workflow-language/cwl-website/edit/new-site/content/_data/home.yml, the image in - icon: noun_ecosystem_cycle_3389565.png is going a bit over the word "reproducibility". That happened in Brave browser (Chromium-based) and Firefox on my Linux laptop. --- this doesn't happen in my Firefox could you give the resolution so we can debug it?
> 
> My laptop screen is 1366 x 768 px, the browser screen is 1366 x 673 px

And for Firefox, 1366 x 622 px

**Comment by lunacodes** [comment]
@melibleq I just pushed a potential fix. Can you let me know if it's back to normal now? I haven't been able to replicate it on my end so far (I tried a couple of different browser and device combinations)

**Comment by melibleq** [comment]
No, the problem persists :( separately, it looks fine in Firefox Focus on my Android phone

**Comment by lunacodes** [comment]
This should be fixed now. The issue was that their was a set `height` property, that needed to be changed to `min-height`. @melibleq can you confirm if it's fixed for you?

**Comment by melibleq** [comment]
Yes it is, yay! However, now there's an issue with the font scaling - see below, "interoperability" and "reproducibility".

It happens with 100% zoom in both browsers I mentioned earlier (Brave and Firefox, laptop) but it looks fine when I zoom out. Also fine in Firefox Focus - Android.

![image](https://user-images.githubusercontent.com/16723182/152015606-43534fe3-b676-481b-b8c0-e14f7e010dbe.png)

**Comment by swzCuroverse** [comment]
I am seeing the same thing with one of those - but not both.

**Comment by lunacodes** [comment]
@melibleq @swzCuroverse I decreased the font size, and changed the word-break behavior. Can you let me know if you're still seeing the issue?

**Comment by melibleq** [comment]
It looks perfect now! Thank you!

**Comment by lunacodes** [comment]
It seems like everything from this Issue was resolved, so I'm going to close it.
